# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='birthday',
            field=models.DateField(),
        ),
    ]
